dist: trusty
sudo: false
language: cpp

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - g++-5
   - libboost-all-dev
   - libcgal-dev
   - qtbase5-dev

script:
 - cd src
 - mkdir build
 - cd build
 - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake ..
 - cmake --build .. -- -jg2