dist: trusty
sudo: required
language: cpp

notifications:
 email: false

# Install the latest cgal library
before_install:
  - wget https://launchpad.net/ubuntu/+archive/primary/+files/libcgal-dev_4.11-2_amd64.deb
  - sudo dpkg -i libcgal-dev_4.11-2_amd64.deb

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
   - sourceline: 'ppa:beineri/opt-qt592-trusty'
  packages:
   - g++-5
   # Install other dependencies
   - libboost-all-dev
   - qt59base
   - qt59declarative
   - qt59charts-no-lgpl
   # Install these if you have a newer version of Qt libs on your package manager
   # which should be available by default
   # - qtbase5-dev
   # - qtdeclarative5-dev
   # - libqt5charts5-dev

script:
 - cd src
 - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake .
 - cmake --build . -- -j2
