version: '2.1.{build}'

image:
  - Visual Studio 2017

clone_folder: c:\Repos\source

# Enable catched builds, this is much faster
cache:
  - CGAL-Setup.exe -> appveyor.yml
  - C:\CGAL -> appveyor.yml

environment:
  BOOST_ROOT: C:\Libraries\boost_1_58_0
  QT5_ROOT: C:\Qt\5.9.2
  CGAL_ROOT: C:\CGAL\

# QT and Boost are already installed in Appveyor, I just need to get CGAL
before_build:
# Install CGAL
  - if not exist CGAL-Setup.exe
      appveyor DownloadFile https://github.com/CGAL/cgal/releases/download/releases/CGAL-4.10.1/CGAL-4.10.1-Setup.exe
      -FileName CGAL-Setup.exe
  - if not exist %CGAL_ROOT%
      CGAL-Setup.exe /S /D=c:\CGAL
# Build CGAL
  - set CGAL_ROOT=C:\CGAL\
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - cd %CGAL_ROOT%
  - if not exist C:\CGAL\CGAL.sln
      cmake -G "Visual Studio 15 Win64" .
  - if not exist C:\CGAL\bin\libCGAL.dll
      cmake --build .
  # Setup environment
  - set PATH=%PATH%;%CGAL_ROOT%\bin
  - set PATH=%PATH%;%CGAL_ROOT%\auxiliary\gmp\lib
  - set PATH=%PATH%;%QTDIR%\bin
  - set PATH=C:\Program Files\Git\usr\bin;%PATH%

build_script:
  - cmd: >-
      cd src

      mkdir build

      cd build

      cmake c:\Repos\source\src -G "Visual Studio 15 Win64"

      cmake --build . --config "Debug"
