image:
  - Visual Studio 2017

clone_folder: c:\Repos\source

build_script:
  - cmd: >-
      cd src

      mkdir build

      cd build

      cmake c:\Repos\source -G "Visual Studio 15"

      cmake --build . --config "Debug"
