version: '2.1.{build}'

# The Matrix Revolutions
image:
  - Visual Studio 2017
  - Visual Studio 2015
platform:
  - x64

test: off

clone_folder: c:\Repos\source

cache:
  - C:\Repos\source\Pentagonal_Tiling_Dependencies -> appveyor.yml

# Download dependencies
install:
  - ps: if($env:PLATFORM  -eq 'x64') { $env:arch = ' Win64'; } else { $env:arch = ''; } # Null for x86 builds
  - ps: if($env:APPVEYOR_BUILD_WORKER_IMAGE  -eq 'Visual Studio 2017') { $env:compiler = 'Visual Studio 15 2017'; }
  - ps: if($env:APPVEYOR_BUILD_WORKER_IMAGE  -eq 'Visual Studio 2015') { $env:compiler = 'Visual Studio 14 2015'; }
  - if not exist Pentagonal_Tiling_Dependencies (mkdir Pentagonal_Tiling_Dependencies)
  - cd Pentagonal_Tiling_Dependencies
  - if not exist deps.7z (
      appveyor DownloadFile https://github.com/justinjk007/Pentagonal-tiling/releases/download/v2.1/vcpkg-export-20180112-110203.7z
      -FileName deps.7z )
  - if not exist C:\Repos\source\Pentagonal_Tiling_Dependencies\vcpkg-export-20180112-110203\.vcpkg-root (
      7z e deps.7z -y -spf -oC:\Repos\source\Pentagonal_Tiling_Dependencies )
      # -y   => Yes to all prompts
      # -spf => Use fully qualified file paths
      # -o   => Set Output directory

build_script:
  - cd C:\Repos\source\
  - mkdir build
  - cd build
  # Anything b/w %% will get replaced by the value of that environment variable
  - cmake -D CMAKE_TOOLCHAIN_FILE=C:/Repos/source/Pentagonal_Tiling_Dependencies/vcpkg-export-20180112-110203/scripts/buildsystems/vcpkg.cmake C:\Repos\source -G "%compiler%%arch%"
  - cmake --build . --config "Release"
