version: '2.1.{build}'

image:
  - Visual Studio 2017

clone_folder: c:\Repos\source

# Enable catched builds, this is much faster
cache: c:\tools\vcpkg\installed\

# Install dependencies before build using vcpkg
before_build:
  - cmd: >-
      vcpkg install boost:x64-windows

      vcpkg install qt5:x64-windows

      vcpkg install cgal:x64-windows

build_script:
  - cmd: >-
      cd src

      mkdir build

      cd build

      cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake c:\Repos\source\src -G "Visual Studio 15 Win64"

      cmake --build . --config "Debug"
